### ISSUE TITLE
Oh-no! Awesome-lint errors! 😱

### ISSUE THREAD

**Issue by Potherca** [thomasbnt/awesome-web-monetization#4]
When I run [awesome-lint](https://github.com/sindresorhus/awesome-lint) for this repository, it gives 75 errors.

The full list is below, everything marked with an [x] is solved in https://github.com/thomasbnt/awesome-web-monetization/pull/3

The three remaining errors are not in the code.

It is possible to add a awesome-lint as `package.json` and/or github action. If desirable, I can help set this up 👍 

- - -

The full list is:

- [x] `1:1` Git repository must be at least 30 days old
- [x] `1:1` The repository should have "awesome" as a GitHub topic
- [x] `1:1` The repository should have "awesome-list" as a GitHub topic
- [X] `1:1` Missing or invalid Table of Contents
- [X] `11:3` Invalid list item link URL
- [X] `12:3` Invalid list item link URL
- [X] `13:3` Invalid list item link URL
- [X] `14:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `14:7` Invalid list item link URL
- [X] `15:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `15:7` Invalid list item link URL
- [X] `16:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `16:7` Invalid list item link URL
- [X] `17:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `17:7` Invalid list item link URL
- [X] `18:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `18:7` Invalid list item link URL
- [X] `19:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `19:7` Invalid list item link URL
- [X] `20:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `20:7` Invalid list item link URL
- [X] `21:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `21:7` Invalid list item link URL
- [X] `22:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `22:7` Invalid list item link URL
- [X] `23:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `23:7` Invalid list item link URL
- [X] `24:5` Incorrect indentation before bullet: remove 2 spaces
- [X] `24:7` Invalid list item link URL
- [X] `39:1` Rules should use ---
- [X] `53:8` Misaligned table fence
- [X] `53:91` Misaligned table fence
- [X] `53:177` Misaligned table fence
- [X] `53:295` Misaligned table fence
- [X] `53:497` Misaligned table fence
- [X] `54:8` Misaligned table fence
- [X] `54:15` Misaligned table fence
- [X] `54:73` Misaligned table fence
- [X] `54:93` Misaligned table fence
- [X] `54:96` Misaligned table fence
- [X] `61:8` Misaligned table fence
- [X] `61:85` Misaligned table fence
- [X] `83:1` Don’t add a trailing . to headings
- [X] `85:1` Marker style should be -
- [X] `86:1` Marker style should be -
- [X] `87:1` Marker style should be -
- [X] `88:1` Marker style should be -
- [X] `89:1` Marker style should be -
- [X] `90:1` Marker style should be -
- [X] `90:3` Don’t pad link with inner spaces
- [X] `91:1` Marker style should be -
- [X] `92:1` Marker style should be -
- [X] `93:1` Marker style should be -
- [X] `94:1` Marker style should be -
- [X] `95:1` Marker style should be -
- [X] `96:1` Marker style should be -
- [X] `97:1` Marker style should be -
- [X] `98:1` Marker style should be -
- [X] `99:1` Marker style should be -
- [X] `100:1` Marker style should be -
- [X] `104:1` Marker style should be -
- [X] `104:13` Invalid list item link
- [X] `105:1` Marker style should be -
- [X] `109:1` Marker style should be -
- [X] `110:1` Marker style should be -
- [X] `114:1` Marker style should be -
- [X] `122:1` Marker style should be -
- [X] `124:1` Marker style should be -
- [X] `130:1` Marker style should be -
- [X] `131:1` Marker style should be -
- [X] `132:1` Marker style should be -
- [X] `133:1` Marker style should be -
- [X] `134:1` Marker style should be -
- [X] `134:28` Invalid list item link
- [X] `138:1` Rules should use ---

**Comment by thomasbnt** [comment]
Oh thanks for that ! I jus edited topics. One more left, waiting for 30 days :D 

> It is possible to add a awesome-lint as package.json and/or github action. If desirable, I can help set this up :+1: 

What's that for on that repo?

**Comment by Potherca** [comment]
Currently, there isn't a Github Action (or external CI) that runs the awesome-linter against commits or merge-requests. Adding a Github Action for this will make an  ✅ or ❌ show up for commits and MRs, so you can see if they pass the linter (or not)

I've created two example here:

- https://github.com/potherca-contrib/awesome-web-monetization/pull/1
- https://github.com/potherca-contrib/awesome-web-monetization/pull/2

The first uses NPM to run the awesome linter. The benefit of this is that anyone who wants add something can just run `npm i && npm test` locally, and the linter will run. The downside is that this means adding a `package.json`, `package-lock.json`, and `.gitignore` file, besides the github actions file.

The second example doesn't add any of these files but instead uses a Github Action that provides awesome-lint. If you expect most people to edit the `readme.md` on Github anyway, it saves adding superfluous files to the repo.

You can see the builds here:

- https://github.com/potherca-contrib/awesome-web-monetization/runs/792812977?check_suite_focus=true
- https://github.com/potherca-contrib/awesome-web-monetization/runs/792812585?check_suite_focus=true

(Please note that the errors you see there are of _my_ repo, not yours...)

If you would like to use either one in this repo, just let me know which one... I can easily open an MR for it here 😁 .

**Comment by thomasbnt** [comment]
Oh so cool ! Adding Awesome-lint NPM could be good for so as not to waste too much time checking for errors every time. :octopus: 

You can create a new PR for adding this Action to this repository and I accept this new feature :clap:

**Comment by thomasbnt** [comment]
Okay thanks you for helped me @Potherca ! I forget to add `package.json` for working correctly.. ^^"

**Comment by Potherca** [comment]
Hey, you got it to work! Well done! 👍 And the final warning "Git repository must be at least 30 days old" should also be resolved now 🎉

**Comment by Potherca** [comment]
Shouldn't this be closed, as the linter passes and https://github.com/sindresorhus/awesome/pull/1812 has been merged?

**Comment by thomasbnt** [comment]
Of course @Potherca ! He merged yesterday 😄☕
